create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  phone text not null,
  reservation_date date not null,
  reservation_time text not null,
  guests integer not null check (guests between 1 and 12),
  notes text not null default '',
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create index if not exists reservations_date_idx
  on public.reservations (reservation_date);

create table if not exists public.members (
  id bigint generated by default as identity primary key,
  phone text not null unique,
  name text not null,
  points integer not null default 120 check (points >= 0),
  visits integer not null default 0 check (visits >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.redemptions (
  id bigint generated by default as identity primary key,
  member_id bigint not null references public.members(id),
  reward text not null,
  points_cost integer not null check (points_cost > 0),
  created_at timestamptz not null default now()
);

create index if not exists redemptions_member_idx
  on public.redemptions (member_id);

alter table public.reservations enable row level security;
alter table public.members enable row level security;
alter table public.redemptions enable row level security;

create or replace function public.redeem_reward(
  p_phone text,
  p_reward text,
  p_cost integer
)
returns table (
  name text,
  phone text,
  points integer,
  visits integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  redeemed_member public.members%rowtype;
begin
  update public.members
    set points = members.points - p_cost
    where members.phone = p_phone
      and members.points >= p_cost
    returning members.* into redeemed_member;

  if redeemed_member.id is null then
    raise exception 'insufficient_points';
  end if;

  insert into public.redemptions (member_id, reward, points_cost)
  values (redeemed_member.id, p_reward, p_cost);

  return query
    select
      redeemed_member.name,
      redeemed_member.phone,
      redeemed_member.points,
      redeemed_member.visits;
end;
$$;

revoke all on function public.redeem_reward(text, text, integer) from public;
grant execute on function public.redeem_reward(text, text, integer) to service_role;
